# Generated by Django 2.1.2 on 2018-11-27 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20181127_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='level',
            field=models.IntegerField(blank=True, choices=[(1, 'level 1'), (2, 'level 2'), (3, 'level 3')], default=1),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='sex',
            field=models.CharField(blank=True, choices=[('female', 'female'), ('male', 'male')], default='', max_length=10),
        ),
    ]
