# Generated by Django 2.1.2 on 2018-11-27 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20181127_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
