version: "3"
services:
  education:
    image: mysql/mysql-server:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=cuong
      - MYSQL_PASSWORD=cuong
      - MYSQL_DATABASE=education
    volumes:
      - .:/education
  web:
    links:
      - education
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/ESM
    image: django
    stdin_open: true
    tty: true
    ports:
      - 8080:8080