# Generated by Django 2.1.2 on 2018-11-27 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_module'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Major',
        ),
    ]
