# Generated by Django 2.1.2 on 2018-11-27 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_delete_major'),
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('major_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('history', models.TextField(blank=True, max_length=1000)),
            ],
        ),
    ]
