# Generated by Django 2.1.2 on 2018-11-27 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_major'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Major',
        ),
    ]
