# Generated by Django 2.1.2 on 2018-11-28 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_delete_major'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='time',
        ),
    ]
