# Generated by Django 2.1.2 on 2018-11-28 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_remove_module_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
