# Generated by Django 2.1.2 on 2018-11-28 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_init'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='full_name',
        ),
    ]
